version: '2'

services:
  gitlab:
    image: gitlab/gitlab-ce
    restart: always
    stdin_open: true
    tty: true
    network_mode: host
    hostname: git.zenvv.com
    #ports:
    #    - 80:10080
    #    - 443:10443
    #    - 22:10022
    environment:
        - GITLAB_OMNIBUS_CONFIG="external_url 'https://git.zenvv.com/';"
    volumes:
        - /etc/localtime:/etc/localtime
        - /opt/etc/gitlab/config:/etc/gitlab:Z
        - /opt/etc/gitlab/logs:/var/log/gitlab:Z
        - /opt/etc/gitlab/data:/var/opt/gitlab:Z

