version: '2'

services:
  # from sameersbn/gitlab
  # default, username: root, password: 5iveL!fe
  gitlab:
    image: lark.io/gitlab:stable
    restart: always
    stdin_open: true
    tty: true
    #links:
    #    - redis:redisio
    #    - postgresql:postgresql
    network_mode: host
    # ports:
    #    - 80
    #    - 22
    environment:
        - DEBUG=false
        - TZ=Asia/Kolkata
        - GITLAB_TIMEZONE=Kolkata

        #>pwgen -Bsv1 64
        - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string

        - GITLAB_HOST=localhost
        - GITLAB_PORT=80
        - GITLAB_SSH_PORT=22
        - GITLAB_RELATIVE_URL_ROOT=

        - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
        - GITLAB_NOTIFY_PUSHER=false

        - GITLAB_EMAIL=peter@uskee.org
        - GITLAB_EMAIL_REPLY_TO=peter@uskee.org
        - GITLAB_INCOMING_EMAIL_ADDRESS=peter@uskee.org

        - GITLAB_BACKUP_SCHEDULE=daily
        - GITLAB_BACKUP_TIME=01:00

        #- SMTP_ENABLED=false
        #- SMTP_DOMAIN=www.example.com
        #- SMTP_HOST=smtp.gmail.com
        #- SMTP_PORT=587
        #- SMTP_USER=mailer@example.com
        #- SMTP_PASS=password
        #- SMTP_STARTTLS=true
        #- SMTP_AUTHENTICATION=login

        #- IMAP_ENABLED=false
        #- IMAP_HOST=imap.gmail.com
        #- IMAP_PORT=993
        #- IMAP_USER=mailer@example.com
        #- IMAP_PASS=password
        #- IMAP_SSL=true
        #- IMAP_STARTTLS=false
    volumes:
        - /opt/gitlab_root/log:/var/log/gitlab
        - /opt/gitlab_root/data:/home/git/data

