version: '2'

services:
  # from redis
  redis:
    image: redis
    restart: always
    ports:
        - 6379:6379
    volumes:
        - /opt/redis_root/log:/var/log/redis
        - /opt/redis_root/data:/var/lib/redis

