version: '2'

services:
  gitlab:
    extends:
        file: base/gitlab-ce.yml
        service: gitlab
    image: gitlab/gitlab-ce:9.0.0-rc7.ce.0
    network_mode: default
    ports:
        - "10080:80"
        - "10443:443"
        - "10022:22"
