version: "2"

#docker exec yaml_mattermost_app_1 mattermost roles system_admin peter@uskee.org
#docker exec yaml_mattermost_app_1 mattermost roles system_admin peter
#docker exec yaml_mattermost_app_1 mattermost team add zenvv peter

services:
  mattermost_db:
    image: mattermost/mattermost-prod-db
    restart: unless-stopped
    volumes:
      - /opt/etc/mattermost/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    # uncomment the following to enable backup
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1

  mattermost_app:
    image: mattermost/mattermost-prod-app
    restart: unless-stopped
    links:
      - mattermost_db:db
    ports:
      - "8000:8000"
    volumes:
      - /opt/etc/mattermost/mattermost/config:/mattermost/config:rw
      - /opt/etc/mattermost/mattermost/data:/mattermost/data:rw
      - /opt/etc/mattermost/mattermost/logs:/mattermost/logs:rw
      - /opt/etc/mattermost/mattermost/plugins:/mattermost/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json
